### ISSUE TITLE
Paper appendix

### ISSUE THREAD

**Issue by expectopatronum** [zhangrh93/InvertibleCE#1]
Hi,
thanks for the great work! I am currently trying to better understand "Figure 1". It mentions that the full version for this explanations can be found in the appendix, however, I was not able to find the appendix. Could you please point me let me know where to find it?

Thanks and best regards
Verena

**Comment by zhangrh93** [comment]
Hi,
The whole appendix is too large, including too many images, over 100m, so we removed them in the final arxiv version. They are mostly explanations with different parameters. You can have a try to the colab notebook to really see the explanations.

Regards
Ruihan

**Comment by expectopatronum** [comment]
Hi, thanks for the quick response! I am running the Colab now but it doesn't answer my questions unfortunately. 
I am wondering mainly:
1) What is the similarity score mentioned in Figure 1? It is not mentioned elsewhere in the paper.
2) What are the Concept Weight and Contributions mentioned in Figure 1? Is it the variable you called "feature importance"? 
3) Is the formula C_k,l(A) = ... which is described in section "Weight Estimation" somehow related to the Figure?
4) The numbers Similarity Score x Concept Weight in Figure 1 do not add up to 9.095. Is this because not all concepts are displayed or the bias term is missing? Or am I missing something entirely?

I am looking forward to your answers. Also feel free to send the appendix to verena.praher [at] jku.at

Best regards
Verena

**Comment by zhangrh93** [comment]
Simply said, our method transfered the CNN model to a linear model y=wx.

1. Then similarity score is the x value, the concept score (GAP(S)), which refers to the similarity of related area in target instance to the concept prototype.
2. The concept weight is the w. Contributions is the wx without adding them together, or the percentage of each concept in the total contribution. It measures how important each concept is for the given instance in the final prediction.
3. As mentioned in the paper, this is the formula in the figure. GAP(S) refer to concept similarity (concept score), PW is the concept weight. GAP(S)PW is the contribution.
4. Yes, as we only shows 3 out of 15 concepts. The shown 3 concepts contributes the most to each class.

Quite sorry, I only can email you the appendix next week.
